### ISSUE TITLE
CSS pull transition for anchor

### ISSUE THREAD

**Issue by herculeshayer** [herculeshayer/portfolio-website#7]
add effect on link hover -- it should pull toward user upon hover

**Comment by Sarthak88221** [comment]
Hello

**Comment by Sarthak88221** [comment]
Hello, i got a query regarding this .Do you want to pull the nav menu items on hover and i mean if we hover on lets say "about" it should be pulled towards the user?

**Comment by herculeshayer** [comment]
Hey,

What I'm trying to do is "pull" the projects listed on the home page using CSS animations

When the user hovers over the link it'll appear to be pulled toward them.

I wasn't planning on having the navbar links have a similar function but if you'd like you're more than welcome to implement a solution!

**Comment by herculeshayer** [comment]
Hey @Sarthak88221 , let me know if you'd like to work on something in any of my repositories. 

If you find another solution to this issue, feel free to make a pull-request and I'll check it out.

**Comment by Sarthak88221** [comment]
okayy sure will send the request today @herculeshayer

**Comment by herculeshayer** [comment]
@Sarthak88221 if this isn't what you'd like to do. I've created another issue on this repo you can check out. 

I'm leaving it for you. It's not exactly necessary to complete but you're more than welcome to check it out.

[Navbar Issue #10 - Portfolio Website](https://github.com/herculeshayer/portfolio-website/issues/10)
